In [ ]:
import keras

In [ ]:
from keras.datasets import mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


[link text](https://)

In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
y_train.shape

(60000,)

In [ ]:
x_test.shape

(10000, 28, 28)

In [ ]:
y_test.shape

(10000,)

In [ ]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [ ]:
y_train[0]

5

In [ ]:
x_train = x_train.reshape(60000,784)
x_test = x_test.reshape(10000,784)

In [ ]:
x_train[0]
x_train = x_train.astype("float32")
x_test = x_test.astype("float32")
##int,float division;same unit division

In [ ]:
x_train/=255
x_test/=255

###why we are dividing by 255 --to normalize the values

In [ ]:
y_train = keras.utils.to_categorical(y_train,10)
y_test = keras.utils.to_categorical(y_test,10)

In [ ]:
y_train[5]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(128,activation = "relu",input_shape = (784,)))
model.add(Dense(256,activation = "relu"))
model.add(Dense(10,activation = "softmax"))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 10)                2570      
                                                                 
Total params: 136,074
Trainable params: 136,074
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [ ]:
history = model.fit(x_train,y_train,batch_size=128,epochs=10,validation_data=(x_test,y_test))

Epoch 1/10
469/469 [==============================] - 6s 10ms/step - loss: 0.2996 - accuracy: 0.9135 - val_loss: 0.1500 - val_accuracy: 0.9550
Epoch 2/10
469/469 [==============================] - 3s 7ms/step - loss: 0.1190 - accuracy: 0.9655 - val_loss: 0.1047 - val_accuracy: 0.9672
Epoch 3/10
469/469 [==============================] - 4s 7ms/step - loss: 0.0803 - accuracy: 0.9753 - val_loss: 0.0863 - val_accuracy: 0.9723
Epoch 4/10
469/469 [==============================] - 4s 9ms/step - loss: 0.0588 - accuracy: 0.9822 - val_loss: 0.0801 - val_accuracy: 0.9760
Epoch 5/10
469/469 [==============================] - 4s 8ms/step - loss: 0.0462 - accuracy: 0.9855 - val_loss: 0.0758 - val_accuracy: 0.9763
Epoch 6/10
469/469 [==============================] - 3s 7ms/step - loss: 0.0388 - accuracy: 0.9874 - val_loss: 0.0735 - val_accuracy: 0.9775
Epoch 7/10
469/469 [==============================] - 3s 7ms/step - loss: 0.0290 - accuracy: 0.9908 - val_loss: 0.0737 - val_accuracy: 0.9782
Epoch

In [ ]:
score = model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0747 - accuracy: 0.9782


In [ ]:
score[0] #test loss

0.07472730427980423

In [ ]:
score[1] #test accuracy

0.9782000184059143

In [ ]:
model.predict(x_test[0:1])

1/1 [==============================] - 0s 97ms/step


array([[1.2716886e-09, 1.7918856e-08, 1.6760234e-07, 3.3270986e-05,
        1.0242199e-11, 3.4209581e-08, 6.3268042e-14, 9.9996519e-01,
        1.0920909e-06, 3.8780229e-07]], dtype=float32)

In [ ]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)